import Head from "next/head";
import { getArticles } from "./api/getArticles";

export default function Home({articlesResponse}: any) {
  console.log(articlesResponse)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1>Articles</h1>
      </main>
    </>
  );
}