import Head from "next/head";
import { getArticles } from "./api/getArticles";


export const getStaticProps = (async () => {
  const articlesResponse = await getArticles({ limit: 10 });

  return {
    props: {
      articlesResponse,
    }
  }
})

export default function Home({articlesResponse}) {
  console.log(articlesResponse)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1>Articles</h1>
        <ul>
          {articlesResponse.contents.map((article) => (
            <li key={article.id}>
              <h2>{article.title}</h2>
              <p>{article.createdAt}</p>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
